language: go

go:
  - 1.13.x

services:
  - docker

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - make lint
  - make ci
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)